spring:
  application:
    name: billing-job

  datasource:
    url: jdbc:postgresql://localhost:5432/batch_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  sql:
    init:
      mode: always